@echo off
echo Starting AI Cable Validation System...
echo Starting Backend...
start cmd /k "cd backend && npm run start"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo System is starting up. Please wait for browser to open at http://localhost:3000
